const WHITE_PAPER = "⬜️";
const RED_PAPER = "🟥";
const DURATION = 1000000000;

const BOARD = [
  WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER,
  WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER,
  WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER,
  WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER,
  WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER,
  WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER,
  WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER,
  WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER,
  WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER,
  WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER, WHITE_PAPER,
];

function renderBoard() {
  let boardItems = "";
  for (let index = 0; index < BOARD.length; index++) {
    boardItems += BOARD[index];
    if (index % 10 === 9) {
      boardItems += "\n";
    }
  }
  return boardItems;
}
function delay() {
  for (let index = 0; index < DURATION; index++) {

  }
}

function createPattern() {
  for (let index = 0; index < BOARD.length; index++) {
    if ((index % 4) - 1 === 0) {
      BOARD[index] = RED_PAPER;
    }
  }
}

function play() {
  console.log(renderBoard());

  delay();
  console.clear();
  createPattern();
  console.log(renderBoard());
}

play();
